version: "3.8"

services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto:/mosquitto/config
    restart: always

  simulator:
    build: 
       dockerfile: Dockerfile
       context: ./simulator
    container_name: simulator
    depends_on:
      - mosquitto
    environment:
      - MQTT_BROKER=mosquitto
      - MQTT_PORT=1883
    restart: on-failure

  